version: 2

jobs:
  build:
    docker:
      - image: golang:1.12
    working_directory: /eucalytus/session
    steps:
      - checkout
      - run:
          name: "Build & Test"
          command: GO111MODULE=on go test